default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: 127.0.0.1
  port: 5432
  username: iidutra
  password: 140795

development:
  <<: *default
  database: DevcampPortifolio_development

test:
  <<: *default
  database: DevcampPortifolio_test

production:
  <<: *default
  database: DevcampPortifolio_production
  username: DevcampPortifolio
  password: <%= ENV['DEVCAMPPORTIFOLIO_DATABASE_PASSWORD'] %>
